task3 completed
AaronMqz/React-Program-Epam pull request #4
Opened 2022-07-01 20:27 UTC by AaronMqz

this version is compatible with the main branch

2022-07-04 20:39 UTC, yhormanp-epam requested changes
Great implementation.
The proptypes were used correctly.
There is just one issue, one the components needs to specify the proptypes for the property expected.

Apart from that, everything well implemented

2022-07-04 20:39 UTC, yhormanp-epam commented on netflix_roulette/src/components/Title/Title.component.js
> +  );
Proptype must be used to validate the children sent and the type of data expected

2022-07-08 01:17 UTC, AaronMqz commented on netflix_roulette/src/components/Title/Title.component.js
> +  );
proptype was added

2022-07-08 20:37 UTC, yhormanp-epam approved these changes
All the acceptance criteria was correctly implemented. 

Excellent job

2022-07-08 20:37 UTC, merged